
const Mongoose = require('mongoose')
const Schema = Mongoose.Schema

const termsSchema = new Schema({
    termsHtml: {
        type: String
    },
    version: {
        type: Number,
        default: 1
    },
    webUrl: {
        type: String
    }

}, { timestamps: true });

let term = Mongoose.model('termsAndCondition', termsSchema);

{/* <img src="/assets/images/light.png" style="margin: 20px auto;display: block;"></img> */ }
term
    .update({

    }, {

        $set: {
            termsHtml: `<!doctype html>
            <html lang="en">
            
            <head>
              <meta charset="utf-8">
              <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
              <title>Light Terms And Conditions</title>
              <style> 
              #color{
                color:white;
              }
              
              .Center { 
                  width:200px; 
                  height:200px; 
                  position: fixed; 
                  bottom: 70%; 
                  left: 50%; 
                  margin-left: -100px;
                
              } 
              .my_text
              {
                  font-family:    Museo sans, rounded;
                  font-size:      15px;
            
              }
              body {
               
                    height: 200px;      
                    background-image: linear-gradient(-90deg, #4A96D4,#6EDACC); /* Standard syntax (must be last) */
                               
              }
             
          </style> 
            
            </head>
            
            <body>
              <div id = "color" class = "my_text">
                <div id= "color">
              <b>  Terms & Conditions </b><br>
                </div>
                <h4> 1. GENERAL INFORMATION </h4>
              <h4>  1.1 LIGHT INC. PRODUCTS</h4>
                <p>These Terms & Conditions (these “Terms”) contain the terms and conditions on which we supply content, products or services listed on www.lightforcancer.com (the “Website”), through our applications (the “Apps”) or via other delivery methods to you (collectively referred to as the “Product” or “Products”). Please read these terms and conditions carefully before ordering any Products from the Website or third party App stores (e.g. the Apple App Store, the Android Play Store, Amazon, etc.).
                 </p>
                 <p>
                 The terms “Light,” “us” or “we” refers to Light Inc. The term “Device” refers to the device which is used to access the Products including but not limited to computers, smart phones and tablets. The term “you” refers to the user of the Products. 
                 </p>
                 <p>
                 When you order (“Order”) any Products, or otherwise use or access the Products, you agree to be bound by these Terms and all applicable laws, rules and regulations. You may also be asked to click “I accept” at the appropriate place prior to your purchase of access to the Products. At such time, if you do not click “I accept”, you may not be able to complete such purchase or gain such access. By using the Products, you indicate that you accept these Terms and that you agree to abide by them. If you do not agree to these Terms, please refrain from using the Products.
                 </p>
                 <p>
                 Our contact email address is info@lightforcancer.com. All correspondence to Light should be sent to this contact email address.
                 </p>
                 <h4>1.2 ARBITRATION NOTICE AND CLASS ACTION WAIVER</h4>
                 <p>PLEASE NOTE THAT THESE TERMS CONTAIN AN ARBITRATION CLAUSE. EXCEPT FOR CERTAIN TYPES OF DISPUTES MENTIONED IN THE ARBITRATION CLAUSE, YOU AND LIGHT AGREE THAT DISPUTES RELATING TO THESE TERMS OR YOUR USE OF THE PRODUCTS WILL BE RESOLVED BY MANDATORY BINDING ARBITRATION, AND YOU AND LIGHT WAIVE ANY RIGHT TO PARTICIPATE IN A CLASS-ACTION LAWSUIT OR CLASS-WIDE ARBITRATION.</p>
                <h4>1.3 BASIS OF LICENSE</h4>
                <p>(a) These Terms and the Order set out the whole agreement between you and us for the supply of the Products. In order to participate in certain Products, you may be required to agree to additional terms and conditions; those additional terms are hereby incorporated into these Terms. Where such terms are inconsistent with these Terms, the additional terms shall control.<br>
                (b) Please check that the details in these Terms and on the Order are complete and accurate before you use or commit yourself to purchase the Products. If you think that there is a mistake, please make sure that you ask us to confirm any changes in writing, as we only accept responsibility for statements and representations made in writing by an officer of Light.<br>
                (c) AS PART OF YOUR USE OF THE PRODUCTS, YOU AFFIRMATIVELY CONSENT TO THE PROCESSING AND STORAGE OF YOUR PERSONAL INFORMATION IN THE UNITED STATES, INCLUDING THE PROCESSING AND STORING OF YOUR PERSONAL INFORMATION IN THE UNITED STATES FOR THE PURPOSES OF PROCESSING PAYMENTS AND TRACKING INDIVIDUAL USE OF THE PRODUCTS. BY USING THE PRODUCTS, YOU ACKNOWLEDGE THAT YOU UNDERSTAND AND AGREE THAT THE UNITED STATES MAY NOT HAVE THE SAME LEVEL OF PROTECTIONS FOR YOUR PERSONAL INFORMATION THAT EXIST IN YOUR COUNTRY OF RESIDENCE, AND YOU NONETHELESS CONSENT TO THE PROCESSING AND STORAGE OF YOUR PERSONAL INFORMATION IN THE UNITED STATES. WE WILL TAKE MEASURES AS REQUIRED TO COMPLY WITH APPLICABLE LAW REGARDING THE TRANSFER, STORAGE AND USE OF CERTAIN PERSONAL INFORMATION.</p>
                <h4>1.4 CHANGES TO TERMS</h4>
                <p>Light Inc. reserves the right to change or update these Terms, or any other of our policies or practices, at any time, and will notify users by posting such changed or updated Terms on this page. Any changes or updates will be effective immediately upon posting to www/lightforcancer.com or the Light mobile app. Your continued use of the Products constitutes your agreement to abide by the Terms as changed. Under certain circumstances we may also elect to notify you of changes or updates to our Terms by additional means, such as pop-up or push notifications within the Products or email.</p>
                <h4>2. MEMBERSHIPS AND SUBSCRIPTIONS</h4>
                <h4>2.1 BECOMING A MEMBER</h4>
                <p>(a) You may sign up as a registered user of the Products free of charge (a “Member”). To become a Member you need to go to the relevant section of the Products and sign up. You are responsible for maintaining the confidentiality of your account and password and for restricting access to your Device.<br>
                (b) In the course of your use of the Products, you may be asked to provide certain personalized information to us (such information is referred to hereinafter as “User Information”). This User Information may include information from your Facebook and similar social networking profiles. Our information collection and use policies with respect to the privacy of such User Information are set forth in the Light Privacy Policy. You acknowledge and agree that you are solely responsible for the accuracy and content of User Information, and you agree to keep it up to date.<br>
                (c) By placing an Order through the Products, you warrant that:<br>
                (i) You are legally capable of entering into binding contracts; <br>(ii) All registration information you submit is truthful and accurate; <br>(iii) You will maintain the accuracy of such information; and <br>(iv) Your use of the Products does not violate any applicable law or regulation.</p>
                <h4>2.2 ONCE A MEMBER</h4>
                <p>You are responsible for maintaining the confidentiality of your account, password and other User Information and for restricting access to your Device to further help protect such information. You are responsible for updating your User Information.</p>
                <h4>2.3 USE OF LIGHT BY MINORS</h4>
                <p>You must be 18 years of age, or the age of majority in your province, territory or country, to sign up as a registered user of the Products. Individuals under the age of 18, or the applicable age of majority, may utilize the Products only with the involvement and consent of a parent or legal guardian, under such person's account and otherwise subject to these Terms.</p>
                <h4>2.4 MEMBERSHIP</h4>
                <p>As a Light Member you will receive access to certain sections, features and functions of the Products or the entire Product content for an extended period of time, which is not available to non-members.<br>
                By agreeing to become a Member you opt-in to receiving occasional special offer, marketing, survey and Product based communication emails. You can easily unsubscribe from Light commercial emails by following the opt-out instruction in these emails. Light memberships and subscriptions are not transferable and therefore cannot be sold or exchanged or transferred in any way whatsoever.</p>
                <h4>2.5 SUBSCRIPTIONS</h4>
                <p>(a) Light account holders may access the Products in two ways:<br>
                • (i) "Basics" Free Trial: a free-of-charge program, which gives unlimited access for seven days.<br>
                • (ii) Paid Subscription: a subscription fee-based program, which gives access to all content beyond the trial seven days. You will only have access to the Subscription Program while your subscription is active and subsisting. You may have access to a free trial period of the Subscription Program in accordance with certain promotional offers. All subscription services provide access through the Products. You can become a subscriber to the Subscription Program by purchasing a subscription to the Products from the Website, within the Apps or where allowed by the App marketplace partners. <br>
            Please note that if you purchase a subscription through the Apple iTunes Store or our iPhone application, the sale is final, and we will not provide a refund. Your purchase will be subject to Apple’s applicable payment policy, which also may not provide for refunds. If you purchase a subscription through the Google Play store, the sale is final and we will not provide a refund. Your purchase will be subject to Google’s applicable payment policy, which also may not provide for refunds. If you purchase through one or more of our bundle subscription partners, the purchase may be further subject to the Terms and Conditions of such partners, and payment and management of the bundle subscription may be administered by them.<br>
            (b) Light offers monthly and annual subscription options. For the purposes of our monthly and yearly subscriptions, a month constitutes 30 calendar days and a year constitutes 365 calendar days. <br>
            (c) Our “Monthly” subscription is paid in monthly installments. For each month that your monthly subscription is active, you acknowledge and agree that Light Inc. is authorized to charge the same credit card as was used for the initial subscription fee or other payment method as set forth in section 2.5(h) (the “Payment Method”). The monthly renewal subscription fees will continue to be billed to the Payment Method you provided, automatically until cancelled. You must cancel your subscription before it renews each month in order to avoid billing of the next month’s subscription fee to the Payment Method you provided. Refunds cannot be claimed for any partial-month subscription period.<br>
            (d) Our “Yearly” subscription is paid for by an upfront one-off payment with automatic annual renewals. You acknowledge and agree that Light Inc. is authorized to charge the Payment Method used for (i) the initial annual subscription fee at the rate secured at the time of purchase, and (ii) the non-discounted renewal subscription fee(s). You must cancel your subscription before it renews in order to avoid billing of the renewal subscription fee to the Payment Method you provided. Refunds cannot be claimed for any partial subscription period.<br>
            (g) You agree to promptly notify Light of any changes to the Payment Method you provided while any subscriptions remain outstanding. You are responsible for all applicable fees and charges incurred, including applicable taxes, and all subscriptions purchased by you.<br>
            (h) In the course of your use of the Products, Light and its third party payment service provider may receive and implement updated credit card information from your credit card issuer in order to prevent your subscription from being interrupted by an outdated or invalid card. This disbursement of the updated credit card information is provided to Light and Light’s third party payment service provider at the sole election of your credit card issuer. Your credit card issuer may give you the right to opt-out of the update service. Should you desire to do so, please contact your credit card issuer.<br>
            (i) Our obligation to provide the Products only comes into being when we take receipt of your Order. We shall confirm your Order and send you an email to confirm your access to the subscription purchased. Please quote the Order number in all subsequent correspondence with us. Prices in US Dollars and Euros include local taxes. All prices in Pound Sterling include VAT unless otherwise stated. You agree not to hold us responsible for banking charges incurred due to payments on your account. If payment is not received by us from the Payment Method you provided, you agree to pay all amounts due upon demand by us. You agree that you are not permitted to resell any Products purchased through Light for commercial purposes.</p>
                <h4>2.6 DEVICE REQUIREMENTS</h4>
                <p>To enjoy Light via your smartphone or other Device, your Device must satisfy certain system requirements. These requirements can be found on the Website and the Google, Apple and Amazon App marketplaces.</p>
                <h4>2.9 CHANGING FEES AND CHARGES</h4>
                <p>We reserve the right to change our subscription plans or adjust pricing for our service or any components thereof in any manner and at any time as we may determine in our sole and absolute discretion. Except as otherwise expressly provided for in these Terms, any price changes or changes to your subscription plan will take effect following notice to you.</p>
                <h4>3. CANCELLATION OF SERVICES</h4>
                <h4>3.1 CANCELLATION BY YOU</h4>
                <p>(a) You may cancel a Monthly subscription at any time. Cancellation is effective at the end of the applicable monthly period. </br></br>
                (b) ) You may cancel a Yearly subscription plan at any time. Cancellation is effective at the end of the applicable annual period. </br></br>
                (c) If you purchase a subscription through the Apple iTunes Store or our iPhone application, you may cancel your subscription by cancelling automatic renewal of paid In App Subscriptions by selecting Manage App Subscriptions in your iTunes Account settings and selecting the subscription you want to modify. If you purchase a subscription through the Google Play store you may cancel automatic renewals in account settings under Subscriptions in the Google Play app, or according to the current process outlined by Google Play.</p>

                <h4>3.2 CANCELLATION BY US</h4>
                <p>We may suspend or terminate your use of the Products as a result of your fraud or breach of any obligation under these Terms. Such termination or suspension may be immediate and without notice. A breach of these Terms, includes without limitation, the unauthorized copying or download of our audio or video content from the Products.</p>
                <h4>3.3 PROMOTION AND DISCOUNT CODES</h4>
                <p>Any promotion code or offer (including the Special Discount Pricing Options) provided by us may not be used in conjunction with any other promotion code or offer, past or present. Introductory offers are only available to new users of the Products, except where expressly stated otherwise. Previous users or trial users of the Products do not qualify as new users. No promotion code or discount will apply to corporate or other Community subscriptions. Unless otherwise set forth in the terms of any promotion, all pricing promotions or discounts will apply to the initial period of the subscription, and any renewals will be charged at the non-discounted rate for the type of subscription purchased.</p>
                 <h4>4. PROHIBITED USE OF THE PRODUCTS</h4>
                <p>4.1 You agree not to upload, post, email or otherwise send or transmit or introduce any material that contains software viruses or any other computer code, files or programs designed to interrupt, harm, damage, destroy or limit the functionality of any computer software or hardware or equipment linked directly or indirectly with the Products or the Products themselves. You agree not to interfere with the servers or networks underlying or connected to the Products or to violate any of the procedures, policies or regulations of networks connected to the Products. You may not access the Products in an unauthorized manner.</br></br>
                4.2 You agree not to impersonate any other person while using the Products, conduct yourself in an offensive manner while using the Products, or use the Products for any illegal, immoral or harmful purpose.</br></br>
                4.3 By breaching the provisions of this section 4, you may commit a criminal offense under applicable laws. We may report any such breach to the relevant law enforcement authorities and we may cooperate with those authorities by disclosing your identity to them. In the event of such a breach, your right to use the Products will cease immediately.</br></br>
                4.4 You agree not to use the Products for any purposes related to scientific research, analysis or evaluation of the Products without the express written consent of Light Inc.</p> 
                <h4>5. MATERIALS OFFERED THROUGH THE PRODUCTS</h4>
                <h4>5.1 COPYRIGHT</h4>
                <p>(a) All materials (including software and content whether downloaded or not) contained in the Products are owned by Light Inc. (or our affiliates and/or third party licensors, where applicable), unless indicated otherwise. You agree and acknowledge that the materials are valuable property and that other than any specific and limited license for use of such materials, you shall not acquire any ownership rights in or to such materials. The materials may not be used except as provided for in these Terms, and any other relevant terms and conditions provided to you without our prior written permission.</br></br>
                (b) You acknowledge and agree that certain materials on or in the Products are the property of third party licensors and, without prejudice to any and all other rights and remedies available, each such licensor has the right to directly enforce relevant provisions of section 12 against you.</br></br>
                (c) Audio or video content from Light not explicitly indicated as downloadable may not be downloaded or copied from the Products or any Device.</br></br>
                (d) The Products are not intended for your commercial use. Commercial advertisements, affiliate links, and other forms of solicitation may be removed by us without notice and may result in termination of privileges. You must not use any part of the materials used in or on the Products for commercial purposes without obtaining a written license to do so from us. Material from the Products may not be copied or distributed, or republished, or transmitted in any way, without our prior written consent. Any unauthorized use or violation of these Terms immediately and automatically terminates your right to use the Products and may subject you to legal liability. You agree not to use the Products for illegal purposes (including, without limitation, unlawful, harassing, libelous, invasion of another’s privacy, abusive, threatening or obscene purposes) and you agree that you will comply with all laws, rules and regulations related to your use of the Products. Appropriate legal action may be taken for any illegal or unauthorized use of the Products.</br></br>
                 (e) You may not otherwise download, display, copy, reproduce, distribute, modify, perform, transfer, create derivative works from, sell or otherwise exploit any content, code, data or materials in the Products. If you make other use of the Products, or the content, code, data or materials thereon, except as otherwise provided above, you may violate copyright and other laws of the United States, other countries, as well as applicable state laws and may be subject to liability for such unauthorized use. Light will enforce its intellectual property rights to the fullest extent of the law, including the seeking of criminal prosecution.</p>

                 <h4>5.2 TRADEMARKS</h4>
                <p>Light®, the Light logo and all other Light product or service marks are trademarks of Light. All intellectual property, other trademarks, logos, images, product and company names displayed or referred to on or in the Products are the property of their respective owners. Nothing grants you any license or right to use, alter or remove or copy such material. Your misuse of the trademarks displayed on the Products is strictly prohibited. Light will enforce its trademark rights to the fullest extent of the law, including the seeking of criminal prosecution.</p>
                 <h4>6. AVAILABILITY OF PRODUCTS</h4>
                <p>6.1 Although we aim to offer you the best service possible, we make no promise that the Products will meet your requirements and we cannot guarantee that the Products will be fault free. If a fault occurs in the Products, please report it to us at info@lightforcancer.com and we will review your complaint and, where we determine it is appropriate to do so, correct the fault. If the need arises, we may suspend access to the Products while we address the fault. We will not be liable to you if the Products are unavailable for a commercially reasonable period of time.</br></br>
                6.2 Your access to the Products may be occasionally restricted to allow for repairs, maintenance or the introduction of new facilities or Products. We will restore the Products as soon as we reasonably can. In the event that the Products are unavailable, our usual Order and cancellation deadlines apply.</p>
                 <h4>7. USER MATERIAL</h4>
                <p>7.1 The Products may let you submit material to us: for example, you may be able to upload a photo to your profile, post subjects and comments in the community and comment on various matters in various parts of the Products. You may be able to upload video, images or sounds. In these Terms, we use the term “User Material” to refer to any publicly available material of any kind that you submit to us, including text, files, images, photos, video, sounds and musical or literary works. User Material does not include the account information, Product purchase, or Product use information which you provide in registering for and using Products.</br></br>
                7.2 This section 7 sets out the rights and obligations that each of us have in connection with User Material. If you review or submit User Material, you are agreeing to do so in accordance with these Terms. If you do not want to review or submit User Material in accordance with these Terms, then you should not do so.</br></br>
                7.3 We do not systematically review User Material submitted by you or other users. We are not responsible for the content of User Material provided by you or any other user. We do not necessarily endorse any opinion contained in such material. We make no warranties or representations, express or implied, about User Material, including as to its legality or accuracy.</br></br>
                7.4 We reserve the right, in our sole discretion, to refuse to post or to remove or edit any of your User Material, or to restrict, suspend, or terminate your access to all or any part of the Products, particularly where User Material breaches this section 7, and we may do this with or without giving you any prior notice.</br></br>
                7.5 We may link User Material or parts of User Material to other material, including material submitted by other users or created by Light or other third parties. We may use User Material for our internal business purposes, for example, to examine trends or categories or to promote, market or advertise Light. You acknowledge that we may indirectly commercially benefit from use of your User Material.</br></br>
                7.6 Each time you submit User Material to us, you represent and warrant to us as follows:
                    • (a) You own your User Material or have the right to submit it, and in submitting it you will not be infringing any rights of any third party, including intellectual property rights (such as copyright or trade mark), privacy or publicity rights, rights of confidentiality or rights under contract.</br></br>
                    • (b) Your User Material is not illegal, obscene, defamatory, threatening, pornographic, harassing, hateful, racially or ethnically offensive, and does not encourage conduct that would be considered a criminal offense, and does not give rise to civil liability, violate any law, or is otherwise deemed inappropriate.</br></br>
                    • (c) Your User Material does not advertise any product or service or solicit any business.</br></br>
                    • (d) Your User Material does not identify any individual (including by way or name, address or a still picture or video) under the age of 18 and if User Material identifies any individual over the age of 18, you have that person’s consent to being identified in exactly that way in your User Material; and in submitting your User Material you are not impersonating any other person.</br></br>
                    • (e) You will not collect email addresses of users for the purpose of sending unsolicited email.</br></br>
                    • (f) You will not engage in criminal or tortious activity, including fraud, spamming, spimming, sending of viruses or other harmful files, copyright infringement, patent infringement, or theft of trade secrets or attempt to impersonate another user or person.</br></br>
                    • (g) You will not engage in any automated use of the system, such as using scripts to alter our content.</br></br>
                    • (h) You will not, without authorization, access, tamper with, or use non-public areas of the Products, Light’s computer systems, or the technical delivery systems of Light’s providers.</br></br>
                    • (i) Except as necessary to maintain your own computer security by use of commercial-off-the-shelf anti-virus or anti-malware products, you will not attempt to probe, scan, or test the vulnerability of the Products or any other Light system or network or breach any security or authentication measures.</br></br>
                7.7 We are entitled to identify you to third parties who claim that their rights have been infringed by User Material you have submitted.</br></br>
                7.8 User Material is not considered to be confidential. You agree not to submit any content as User Material in which you have any expectation of privacy. We do not claim any ownership rights in User Material. However, by submitting User Material you hereby grant Light an irrevocable, perpetual, non-exclusive, royalty free, worldwide license to use, telecast, copy, perform, display, edit, distribute and otherwise exploit the User Material you post on the Products, or any portion thereof, and any ideas, concepts, or know how contained therein, with or without attribution, and without the requirement of any permission from or payment to you or to any other person or entity, in any manner (including, without limitation, for commercial, publicity, trade, promotional, or advertising purposes) and in any and all media now known or hereafter devised, and to prepare derivative works of, or incorporate into other works, such User Material, and to grant and authorize sublicenses of the foregoing without any payment of money or any other form of consideration to you or to any third party. Light may include your User Material in Light’s Distribution Content that is made available to others through the Products. Be aware that Light has no control over User Material once it leaves the Products, and it is possible that others may duplicate material found on the Products, including, but not limited to, on other sites on the Internet. You represent and warrant that you own or otherwise control the rights to your User Material. You agree to indemnify Light and its affiliates for all claims arising from or in connection with any claims to any rights in your User Material or any damages arising from your User Material.</br></br>
                7.9 Any inquiries, feedback, suggestions, ideas, other information which is not part of your use of the Products or User Material that you provide to us (collectively, “Submissions”) will be treated as non-proprietary and non-confidential. By transmitting, uploading, posting, e-mailing, or otherwise submitting Submissions to the Products, you grant, and you represent and warrant that you have the right to grant, to Light an irrevocable, perpetual, non-exclusive, royalty free, worldwide license to use, telecast, copy, perform, display, edit, distribute and otherwise exploit the Submissions, or any portion thereof and any ideas, concepts, or know how contained therein, with or without attribution, and without the requirement of any permission from or payment to you or to any other person or entity, in any manner (including, without limitation, for commercial, publicity, trade, promotional, or advertising purposes) and in any and all media now known or hereafter devised, and to prepare derivative works of, or incorporate into other works, such Submissions, and to grant and authorize sublicenses of the foregoing without any payment of money or any other form of consideration to you or to any third party. You also acknowledge that your Submissions will not be returned to you and that Light has no obligation to acknowledge receipt of or respond to any Submissions. If you make a Submission, you represent and warrant that you own or otherwise control the rights to your Submission. You agree to indemnify Light and its affiliates for all claims arising from or in connection with any claims to any rights in any Submission or any damages arising from any Submission.</p> 
                <h4>8. LINKS TO WEBSITES/HOME PAGE</h4>
                <p>8.1 We may provide links to other websites or services for you to access. You acknowledge that any access is at your sole discretion and for your information only. We do not review or endorse any of those websites or services. We are not responsible in any way for:(a) the availability of, (b) the privacy practices of, (c) the content, advertising, products, goods or other materials or resources on or available from, or (d) the use to which others make of these other websites or services. We are also not responsible for any damage, loss or offense caused or alleged to be caused by, or in connection with, the use of or reliance on such websites or services.</br></br>
                8.2 You may link to our home page, provided you do so in a way that is fair and legal and does not damage our reputation or take advantage of it, but you must not establish a link in such a way as to suggest any form of association, approval or endorsement on our part where none exists. You must not establish a link from any website that is not owned by you. The Products must not be framed on any other website, nor may you create a link to any part of the Products unless you have written permission to do so from Light Inc. We reserve the right to withdraw linking permission with written notice. The website from which you are linking must comply in all respects with the content standards set out in our acceptable use policy. If you wish to make any use of material on or in the Products other than that set out above, please address your request to info@lightforcancer.com.</p>
                <h4>9. PRODUCTS DISCLAIMER</h4>
                <p>The information contained in the Products is for general information purposes only. While we endeavor to keep the information up-to-date and correct, we make no representations or warranties of any kind, express or implied, about the completeness, accuracy, reliability, suitability or availability with respect to the Products or the information contained on the Products for any purpose. Any reliance you place on such information is therefore strictly at your own risk.</p>
                
                <h4>10. MEDICAL DISCLAIMER</h4>
                <p>10.1 Light Inc. is a provider of online and mobile meditation content in the health & wellness space. We are not a health care or medical device provider, nor should our Products be considered medical advice. Only your physician or other health care provider can do that. While there is third party evidence from research that meditation can assist in the prevention and recovery process for a wide array of conditions, Light Inc. makes no claims, representations or guarantees that the Products provide a therapeutic benefit.</br></br>
                10.2 Any health information and links on the Products, whether provided by Light or by contract from outside providers, is provided simply for your convenience.</br></br>
                10.3 Any advice or other materials in the Products are intended for general information purposes only. They are not intended to be relied upon and are not a substitute for professional medical advice based on your individual condition and circumstances. The advice and other materials we make available are intended to support the relationship between you and your healthcare providers and not replace it. We are not liable or responsible for any consequences of your having read or been told about such advice or other materials as you assume full responsibility for your decisions and actions. In particular, to the fullest extent permitted by law, we make no representation or warranties about the accuracy, completeness, or suitability for any purpose of the advice, other materials and information published as part of the Products.</br></br>
                10.4 There have been rare reports where people with certain psychiatric problems like anxiety and depression have experienced worsening conditions in conjunction with intensive meditation practice. People with existing mental health conditions should speak with their health care providers before starting a meditation practice.</p>
                <h4>11. END USER LICENSE</h4>
                <p>11.1 Subject to the terms of this license agreement (“License Agreement”), as set out in this section 11, and these other Terms, and your payment of applicable subscription fees, Light Inc. grants you a limited, non-exclusive, revocable license to stream, download and make personal non-commercial use of the Products.</br></br>
                11.2 The Products contain or embody copyrighted material, proprietary material or other intellectual property of Light or its licensors. All right, title and ownership in the Products remain with Light or its licensors, as applicable. The rights to download and use the Products are licensed to you and are not being sold to you, and you have no rights in them other than to use them in accordance with this License Agreement and our other Terms.</br></br>
                11.3 You agree that you will not and you will not assist or permit any third party to:
                    • (a) Copy, store, reproduce, transmit, modify, alter, reverse-engineer, emulate, de-compile, or disassemble the Products in any way, or create derivative works of the Products;</br></br>
                    • (b) Use the Products or any part of them to create any tool or software product that can be used to create software applications of any nature whatsoever;</br></br>
                    • (c) Rent, lease, loan, make available to the public, sell or distribute the Products in whole or in part;</br></br>
                    • (d) Tamper with the Products or circumvent any technology used by Light or its licensors to protect any content accessible through the Products;</br></br>
                    • (e) Circumvent any territorial restrictions applied to the Products; or</br></br>
                    • (f) Use the Products in a way that violates this License Agreement or the other Terms.
                11.4 You may not make the Products available to the public. The Products made available (in whole or in part) are owned by Light Inc. or its licensors and your use of them must be in accordance with these Terms.</p>
                <h4>12. DIGITAL MILLENIUM COPYRIGHT ACT (“DMCA”) NOTICE</h4>
                <p>12.1 We are committed to complying with copyright and related laws, and we require all users of the Products to comply with these laws. Accordingly, you may not store any material or content on, or disseminate any material or content over, the Products in any manner that constitutes an infringement of third party intellectual property rights, including rights granted by copyright law. You may not post, modify, distribute, or reproduce in any way any copyrighted material, trademarks, or other proprietary information belonging to others without obtaining the prior written consent of the owner of such proprietary rights. It is our policy to terminate privileges of any user who repeatedly infringes the copyright rights of others upon receipt of proper notification to us by the copyright owner or the copyright owner’s legal agent.</br></br>
                12.2 If you feel that a posted message is objectionable or infringing, we encourage you to contact us immediately. Upon our receipt of a proper notice of claimed infringement, we will respond expeditiously to remove, or disable access to, the material claimed to be infringing and will commit to resolve the claim between the notifying party and the alleged infringer who provided the content in issue. The proper party to whom you should address such notice is listed below.</br></br>
                12.3 If you believe that your work has been copied and posted on the Products in a way that constitutes copyright infringement, please provide us with the following information:</br>
                    • (a) An electronic or physical signature of the person authorized to act on behalf of the owner of the copyright or other intellectual property interest;</br></br>
                    • (b) A description of the copyrighted work or other intellectual property that you claim has been infringed;</br></br>
                    • (c) A description of where the material that you claim is infringing is located on the Products;</br></br>
                    • (d) Your address, telephone number, and email address;</br></br>
                    • (e) A statement by you that you have a good faith belief that the disputed use is not authorized by the copyright or intellectual property owner, its agent, or the law; and</br></br>
                    • (f) A statement by you, made under penalty of perjury, that the information contained in your report is accurate and that you are the copyright or intellectual property owner or authorized to act on the copyright or intellectual property owner’s behalf.</br></br>
                    • (g) Our designated agent for notice of claims of copyright infringement can be reached as follows:</br>
                By E-Mail: info@lightforcancer.com Subject line: DMCA</p>
                <h4>13. GENERAL TERMS AND CONDITION</h4>
                <h4>13.1 ASSIGNMENT BY US</h4>
                
                <p>Light Inc. may transfer its rights and obligations under these Terms to any company, firm or person at any time if it does not materially affect your rights under it. You may not transfer your rights or obligations under these Terms to anyone else. These Terms are personal to you and no third party is entitled to benefit under these Terms except as set out here.</p>
                <h4>13.2 INDEMNITY BY YOU</h4>
                <p>You agree to defend, indemnify and hold Light and its directors, officers, members, investors, managers, employees and agents harmless from any and all claims, liabilities, costs and expenses, including reasonable attorneys’ fees, arising in any way from your use of the Products, your placement or transmission of any message, content, information, software, or other submissions through the Products, or your breach or violation of the law or of these Terms. Light reserves the right, at its own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you, and in such case, you agree to cooperate with Light defense of such claim.</p>
                <h4>13.3 WARRANTIES AND LIMITATIONS</h4>
                <p>(a) We warrant to you that any Product purchased from us will, on delivery, conform in all material respects with its description and be of reasonably satisfactory quality.</br>
                (b) We warrant that we will use reasonable skill and care in making the Products available to you during your subscription.</br>
                (c) Nothing in this sections 13.3 or otherwise in these Terms shall exclude or in any way limit Light’s liability for: fraud; death or personal injury caused by negligence; or liability to the extent the same may not be excluded or limited as a matter of law.</br>
                (d) The Products and their content are otherwise provided on an “as is” basis and we make no representations or warranties of any kind with respect to them, including as to the accuracy, completeness or currency of the Products or their content. We assume no liability or responsibility for any errors or omissions in the content of the Products, or any failures, delays, or interruptions in the provision of the Products. We disclaim and exclude any express or implied warranties or representations, including any warranties as to merchantability or fitness for a particular purpose of the Products to the broadest extent permitted by law. We make no warranties or representations, express or implied, as to the timeliness, accuracy, quality, completeness or existence of the content and information posted on the Products. We make no warranties or representations, express or implied, for technical accessibility, fitness or flawlessness of the Products. We make no warranties or representations that your use of content and information posted on the Products will not infringe rights of third parties.</br>
                (e) All conditions, warranties and other terms which might otherwise be implied by statute, common law or the law of equity are, to the extent permitted by law, excluded.</p>
                <h4>13.4 NO WAIVER</h4>
                <p>If we delay exercising or fail to exercise or enforce any right available to us under these Terms, such delay or failure does not constitute a waiver of that right or any other rights under these Terms.</p>
                <h4>13.5 FORCE MAJEURE</h4>
                <p>We will not be liable to you for any lack of performance, or the unavailability or failure, of the Products, or for any failure or delay by us to comply with these Terms, where such lack, unavailability or failure arises from any cause beyond our reasonable control.</p>
                <h4>13.6 INTERPRETATION</h4>
                <p>In these Terms, references to the singular include the plural and to the masculine include the feminine, and in each case vice versa.</p>
                <h4>13.7 ELECTRONIC COMMUNICATIONS</h4>
                <p>(a) Applicable laws require that some of the information or communications we send to you should be in writing. When using the Products, you agree to transact with us electronically, and that communication with us will be mainly electronic. We will contact you by e-mail or provide you with information by posting notices on the Products. You agree to this electronic means of communication and you acknowledge that all contracts, notices, information and other communications that we provide to you electronically comply with any legal requirement that such communications be in writing.</br>
                (b) In order to retain a copy, please select “Print,” and select the appropriate printer. If you do not have a printer, you can copy the text and the underlying agreement(s) and paste them into a new document in a word processor or a text editor on your computer and save the text.</br>
                (c) You have the right to receive a paper copy of the communications. To receive a paper copy, please request it by emailing us at info@lightforcancer.com</br>
                (d) We may charge you a reasonable service charge to mail you a paper copy of any communication. We will either include such service charge on our fee schedule or we will first inform you of the charge and provide you with the choice as to whether you still want us to send you a paper copy. Please be sure to state that you are requesting a copy of the particular communication.</br>
                 (f) To retain a copy, you must either have a printer connected to your personal computer or other device or, alternatively, the ability to save a copy through use of printing service or software such as Adobe Acrobat®. If you have a word processor or text editor program on your computer, then you can also copy the text and paste the text into a new document in the word processor or text editor and save the text.</br>
                (g) You can also contact us via email at info@lightforcancer.com to withdraw your consent to receive any future communications electronically, including if the system requirements described above change and you no longer possess the required system. If you withdraw your consent, we may terminate your use of the Products.</br>
                (h) We reserve the right, in our sole discretion, to discontinue the provision of your electronic communications, or to terminate or change the terms and conditions on which we provide electronic communications. We will provide you with notice of any such termination or change as required by law.</p>
                <h4>13.8 NOTICES</h4>
                <p>to Light at info@lightforcancer.com. We may give notice to you at the e-mail address you provide to us when you register, or in any of the ways specified in section 13.7 above. Notice will be deemed received and properly served immediately when posted on the Products or when an e-mail or other electronic communication is sent. In proving the service of any notice via email, it will be sufficient to prove that such e-mail was sent to the specified e-mail address of the addressee.</p> 
                <h4>13.9 ENTIRE AGREEMENT</h4>
                <p>These Terms and any document expressly referred to in them constitute the whole agreement between us and supersede all previous discussions, correspondence, negotiations, previous arrangement, understanding or agreement between us relating to their subject matter. We each acknowledge that neither of us relies on, or will have any remedies in respect of, any representation or warranty (whether made innocently or negligently) that is not set out in these Terms or the documents referred to in them. Each of us agrees that our only liability in respect of those representations and warranties that are set out in this agreement (whether made innocently or negligently) will be for breach of contract. Nothing in this section limits or excludes any liability for fraud.</p>                
                <h4>13.10 THIRD PARTY RIGHTS</h4>
                <p>A person who is not party to these Terms will not, subject to copyright rights, have any rights under or in connection with these Terms.</p> 
                <h4>13.11 OUR LIABILITY</h4>
                <p>(a) We will use reasonable endeavors to remedy faults in the Products. If we fail to comply with these Terms, we will be liable to you only for the purchase price of the Products in question. In addition, we will not be liable for:</br></br>
                • (i) Faulty operation of computers during the registration process or during completion of a subscription or during the transmission of any data and/or for incorrect or overly slow transmission of data by the internet provider and/or any damage that occurs due to information submitted by you not being received by us or not being received promptly or not being considered, as a consequence of technical faults with our software or hardware (whether or not they are within or outside of our control).</br>
                • (ii) Any loss or damage due to viruses or other malicious software that may infect your Device, computer equipment, software, data or other property caused by you accessing, using or downloading from the Products, or from transmissions via emails or attachments received from us.</br>
                • (iii) Any use of websites linked to the Products but operated by third parties.</br></br>
            (b) To the extent permitted by law, Light Inc. and its affiliates, suppliers, clients, or licensors (collectively, the “Protected Entities”) shall not be liable for any consequential, exemplary or punitive damages arising from, or directly or indirectly related to, the use of, or the inability to use, the Products or the content, materials and functions related thereto, your provision of information via the Products, or lost business or lost sales, or any errors, viruses or bugs contained in the Products, even if such Protected Entity has been advised of the possibility of such damages. In no event shall the Protected Entities be liable for or in connection with any content posted, transmitted, exchanged or received by or on behalf of any user or other person on or through the Products. In no event shall the total aggregate liability of the Protected Entities to you for all damages, losses, and causes of action (whether in contract or tort, including, but not limited to, negligence or otherwise) arising from these terms of use or your use of the Products exceed, in the aggregate, the amount, if any, paid by you to Light for your use of the Products.</p> 
                <h4>13.12 ARBITRATION<br>
                PLEASE READ THE FOLLOWING PARAGRAPHS CAREFULLY, AS THEY REQUIRE YOU TO ARBITRATE DISPUTES WITH LIGHT INC., AND LIMIT THE MANNER IN WHICH YOU CAN SEEK RELIEF FROM LIGHT INC.</h4>
                <p>(a) Applicability of Arbitration Agreement. All disputes arising out of, relating to, or in connection with these Terms or your use of the Products that cannot be resolved informally or in small claims court will be resolved through binding arbitration on an individual basis, except that you and Light Inc. are not required to arbitrate any dispute in which either party seeks equitable relief for the alleged unlawful use of copyrights, trademarks, trade names, logos, trade secrets, or patents.</br></br>
                (b) Arbitration Rules.  At the federal level in Canada, commercial arbitration is governed by the Commercial Arbitration Act (CAA). Arbitration will be initiated through the ICC International Court of Arbitrations, Canada.  If the ICC is not available to arbitrate, the parties will select an alternative arbitral forum. The rules of the arbitral forum will govern all aspects of this arbitration, except to the extent those rules conflict with these Terms.</br> 
                If the claim is for $10,000 or less, the party initiating the arbitration may choose whether the arbitration will be conducted</br></br> (1) solely on the basis of documents submitted to the arbitrator; </br></br>(2) through a non-appearance based telephonic hearing; or (3) by an in-person hearing. In the case of an in-person hearing, the proceedings will be conducted at a location which is reasonably convenient for both parties with due consideration of the ability to travel and other pertinent circumstances. If the parties are unable to agree on a location, the determination will be made by the arbitration institution.</br>
                Your arbitration fees and your share of arbitrator compensation will be limited to those fees set forth in the AAA Rules with the remainder paid by Light. If the arbitrator finds that either the substance of your claim or the relief sought in the arbitration is frivolous or brought for an improper purpose (as measured by the standards set forth in Federal Rule of Civil Procedure 11(b)), then the payment of all fees will be governed by the AAA Rules. In such case, you agree to reimburse Light for all monies previously disbursed by it that are otherwise your obligation to pay under the AAA Rules. Regardless of the manner in which the arbitration is conducted, the arbitrator shall issue a reasoned written decision sufficient to explain the essential findings and conclusions on which the decision and award, if any, are based. The arbitrator may make rulings and resolve disputes as to the payment and reimbursement of fees or expenses at any time during the proceeding and upon request from either party made within 14 days of the arbitrator’s ruling on the merits.</br></br>
                (c) Authority of Arbitrator. The arbitrator will decide the jurisdiction of the arbitrator and the rights and liabilities, if any, of you and Light Inc. The dispute will not be consolidated with any other matters or joined with any other cases or parties. The arbitrator will have the authority to grant motions dispositive of all or part of any claim or dispute. The arbitrator will have the authority to award all remedies available under applicable law, the arbitral forum's rules, and the Terms. The arbitrator has the same authority to award relief on an individual basis that a judge in a court of law would have. The award of the arbitrator is final and binding upon you and Light.</br></br>
                (d) Jury Trial Waiver. You and Light Inc. waive any constitutional and statutory rights to go to court and have a trial in front of a judge or a jury. Rather, you and Light Inc. elect to have claims and disputes resolved by arbitration. In any litigation between you and Light Inc. over whether to vacate or enforce an arbitration award, you and Light Inc. waive all rights to a jury trial, and elect instead to have the dispute be resolved by a judge.</br></br>
                (e) Class Action Waiver. WHERE PERMITTED UNDER THE APPLICABLE LAW, YOU AND LIGHT INC AGREE THAT EACH MAY BRING CLAIMS AGAINST THE OTHER ONLY IN YOUR OR OUR INDIVIDUAL CAPACITY AND NOT AS A PLAINTIFF OR CLASS MEMBER IN ANY PURPORTED CLASS OR CONSOLIDATED ACTION. If, however, this waiver of class or consolidated actions is deemed invalid or unenforceable, neither you nor Light Inc. are entitled to arbitration; instead all claims and disputes will be resolved in a court as set forth in section 13.13 below.</br></br>
                (f) Opt-out. YOU MAY OPT-OUT OF THIS ARBITRATION AGREEMENT. If you do so, neither you nor Light Inc. can force the other to arbitrate. To opt-out, you must notify Light Inc. in writing no later than 30 days after first becoming subject to this arbitration agreement. Your notice must include your name and address, and the email address you used to set up your Light account (if you have one), and an unequivocal statement that you want to opt-out of this arbitration agreement. You must send your opt-out notice to the following email addresses: info@lightforcancer.com </br></br>
                (g) Small Claims Court. Notwithstanding the foregoing, either you or Light Inc. may bring an individual action in small claims court.</br></br>
                (h) Public Injunction Exclusion. Notwithstanding the foregoing, you may pursue a claim for public injunctive relief either in court or through arbitration.</br></br>
                (i) Arbitration Agreement Survival. This arbitration agreement will survive the termination of your relationship with Light Inc.</p> 
                <h4>13.13 EXCLUSIVE VENUE</h4>
                <p>To the extent the parties are permitted under these Terms to initiate litigation in a court, both you and Light Inc. agree that all claims and disputes arising out of or relating to the Terms or the use of the Products will be litigated exclusively in Ontario, Canada. </p> 
                <h4>13.14 CHOICE OF LAW</h4>
                <p>Except to the extent they are preempted by Canadian federal law, the laws of the province of Ontario, Canada, other than its conflict-of-laws principles, govern these Terms and any disputes arising out of or relating to these Terms or their subject matter, including tort claims.</p> 
                <h4>13.15 SEVERABILITY</h4>
                <p>If any provision of these Terms is found unenforceable, then that provision will be severed from these Terms and not affect the validity and enforceability of any remaining provisions.
                These Terms are effective and were last updated on May 1, 2020.
                </p> 
               
                

                 </div>
            </body>
            
            </html>`
            , webUrl: "http://ec2-3-21-237-151.us-east-2.compute.amazonaws.com:3000/privacy"
        },
        // $inc: {
        //     version: 1
        // }
    }, {
        upsert: true
    })
    .then((result) => {
        // console.log('result', result);
    })
    .catch((err) => {
        console.log('err', err)
    })
module.exports = term